### ISSUE TITLE
License of CMakeLists.txt

### ISSUE THREAD

**Issue by jgillis** [ampl/coin#12]
We were wondering what the license is of your cmake scripts.
More specifically, are they compatible with LGPL?

**Comment by fdabrandao** [comment]
At least some of the coin-or projects in this repository use Eclipse Public License (EPL). It does not seem compatible with GPL, but I am not sure about LGPL. It would make sense to use the same license for the CMake configuration files but I can make it MIT so that it can be more flexible.

**Comment by jgillis** [comment]
Just EPL would also be great!

**Comment by fdabrandao** [comment]
I have just added the license information to CMakeLists.txt in 1aa9671b990dcd0a01bf78f67c4076e093a46066.
