### ISSUE TITLE
Release 2.10.0?

### ISSUE THREAD

**Issue by fgenoese** [ampl/coin#13]
Is this project still active? There is a new stable release for Cbc (2.10.0). Wondering if you are planning to build static binaries for this version?

**Comment by fdabrandao** [comment]
Thanks for point out the new stable release. We will update the code and generate new binaries soon.

**Comment by fgenoese** [comment]
Hi I saw you updated the code, thanks for that. Would you mind to also upload the binaries to your downloads page?

**Comment by fgenoese** [comment]
@fdabrandao any update on the binaries?

**Comment by fdabrandao** [comment]
We have binaries for Linux and macOS that we can make available if these are enough for you, but the Windows build is failing and that is why we haven't updated the binaries.

**Comment by fgenoese** [comment]
That would be excellent already

**Comment by fdabrandao** [comment]
You can download the binaries for Linux and macOS from: https://ampl.com/builds/upload/releases/coin/2019-11-11/

**Comment by goroderickgo** [comment]
Hi @fdabrandao, do you know if you all will be able to fix the Windows build soon?

**Comment by fdabrandao** [comment]
Hi @goroderickgo, in https://github.com/ampl/coin/blob/master/azure-pipelines.yml there is a azure pipelines configuration for build cbc, bonmin, couenne, and ipopt for Windows, Linux and macOS. For Windows it is currently building but using only mingw. It produces the binaries but they come with dependencies to .DLLs that are usually not available by default. The build status and the upload artifacts are available from https://dev.azure.com/fdabrandao/coin.

**Comment by goroderickgo** [comment]
Hi @fdabrandao, thanks for the quick response! I see about the Windows build... Ideally I would like an executable that doesn't have dependencies to .DLLs, which I've been able to produce those locally before using the "stock" coin/cbc instructions but haven't figured out how to make the executable completely standalone.

**Comment by fdabrandao** [comment]
@fgenoese, @goroderickgo, we have just updated all the binaries at https://ampl.com/dl/open/. The only thing missing now is 32-bit windows which is something that we may drop soon as it is unlikely they are still needed. The Azure Pipelines configuration at https://github.com/ampl/coin/blob/master/azure-pipelines.yml is now complete except for the 32-bit windows binaries.

**Comment by fgenoese** [comment]
Awesome, thank you very much
