### ISSUE TITLE
User requests updated build of CBC

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/coin#15]
We have the following request for a newer version of CBC:

> I'm looking for a 64-bit Windows copy of version 2.9.9 of the CBC Solver. I've attempted downloading it from the link below, but when I run it, it displays a version of 2.9.7 with a build release date of November 24 2015.
> 
> Here's the link: https://ampl.com/dl/open/ipopt/ipopt-win64.zip

I tested this -- but with the cbc link rather than the ipopt link given above -- and confirmed that the version and release date of the currently available binary from our site are as the user states. The GitHub COIN-OR code page shows CBC updated to 2.10.2, however.

**Comment by fdabrandao** [comment]
The code here is updated, but the Windows build is failing and that is why the binaries were not updated yet. This is related to #13 and #11.

**Comment by 4er4er4er** [comment]
I have advised this user to wait for the build issues with 2.10.2 to be fixed. If the fix is not likely to happen quickly, however, it may be worth considering whether it's possible to download and build CBC 2.9.9 for AMPL -- the version that this user requests -- on the chance that a build of that older version won't fail for the same reason.

**Comment by fdabrandao** [comment]
I have just updated all the binaries at https://ampl.com/dl/open/. The only thing missing are 32-bit binaries for Windows (I kept the older version for 32-bits there) which is unlikely someone may still need today.
