### ISSUE TITLE
CBC 2.10.5 requested to fix bug

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/coin#18]
It is requested to update our builds of CBC to version 2.10.5, with the hope of fixing a bug that prevents a solution from being returned after a time limit is reached:

> I am a student who is using cbc throught AMPL to solve mixed-integer linear problems. I have found a bug in the compiled cbc (version 2.10.3), which can be download from ampl website (https://ampl.com/dl/open/cbc/cbc-linux64.zip). The bug is that when I set a time limit for cbc, if that time limit is reached, the solver does not return the best feasible solution founded. This seems to have been fixed in the lastest stable version of cbc (2.10.5), as explained in release notes (https://github.com/coin-or/Cbc/releases/tag/releases%2F2.10.5).

**Comment by fdabrandao** [comment]
We are now building and distributing the following versions:

- Cbc version 2.10.5
- Ipopt version 3.12.13
- Bonmin version 1.8.8
- Couenne version 0.5.8
