### ISSUE TITLE
cmake error on master branch

### ISSUE THREAD

**Issue by fabiencastan** [ampl/coin#2]
I'm trying to build with cmake.
I just cloned the master branch and I get this error:

```
> git clone https://github.com/ampl/coin.git
> cd coin
> mkdir build && cd build
> cmake ..
CMake Error at CMakeLists.txt:532 (target_link_libraries):
  Cannot specify link libraries for target "Cbc-osiUnitTest" which is not
  built by this project.
```

It works with `configure` but I'm interested to use the cmake version.

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/coin/commit/8e34d628442ac9a60cff0c64e74cda4c99df79bc, thanks for reporting!

**Comment by vitaut** [comment]
More out-of-tree build fixes: https://github.com/ampl/coin/commit/f4554b4d92d1ae7941262415062fd5486dece5a8 & https://github.com/ampl/coin/commit/d74908da30ebce30787550ea196cdb125f079adf.
