### ISSUE TITLE
Install header files as well.

### ISSUE THREAD

**Issue by PetterS** [ampl/coin#5]
Currently, only compiled library files are installed via the “INSTALL” target. It would be great if all header files required to use the library were installed as well.

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/coin/commit/9c663a10ded6d0e592d8a160705167305d6619f2. Thanks for reporting!

**Comment by PetterS** [comment]
There seems to be a few header files missing on install:
CoinUtilsConfig.h (used in e.g. CoinMessageHandler.hpp)
ClpConfig.h (used in e.g. ClpModel.hpp)

**Comment by vitaut** [comment]
Missed these, sorry.
