### ISSUE TITLE
CMAKE_POSITION_INDEPENDENT_CODE

### ISSUE THREAD

**Issue by PetterS** [ampl/coin#7]
Is there a perfomance reason the configuration does not always do this:

    set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)

Even if static libraries are built, they may be needed to in turn build shared libraries, which will fail without position independent code. I recently encountered this and had to change CMakeLists.txt.

**Comment by vitaut** [comment]
Apart from potential performance benefits, there is also a CMake convention where `POSITION_INDEPENDENT_CODE` property is set to `False` for static libraries. In any case you can easily set it yourself:

```
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE .
```

**Comment by PetterS** [comment]
Alright, I suppose that is good enough.
